name: latest-commit-date
description: "Get the date of the latest commit"

inputs:
  branch:
    description: "Branch to get history from"
    default: "main"
    required: true

outputs:
  result:
    description: "Your branch name"
    value: ${{ steps.step0.outputs.result }}

runs:
  using: "composite"

  steps:
    - id: current-date
      shell: bash
      run: echo "value=$(date '+%Y-%m-%d')" >> "$GITHUB_OUTPUT"

    - id: latest-commit-date
      shell: bash
      run: echo "value=$(git log -1 --format="%cs")" >> "$GITHUB_OUTPUT"

    - shell: bash
      run: echo "today ${{ steps.current-date.outputs.value }} - commit ${{ steps.latest-commit-date.outputs.value }}"
