name: Latest commit date
description: "An action to retrieve the date of the latest commit on a specified branch."

branding:
  icon: git-commit
  color: gray-dark

inputs:
  branch:
    description: "The name of the branch for which you want to retrieve the latest commit date. Default is 'main'."
    default: main

outputs:
  current-date:
    description: "The current date at the time the action runs."
    value: ${{ steps.current-date.outputs.value }}
  latest-commit-date:
    description: "The date of the latest commit in the Git history of the specified branch."
    value: ${{ steps.latest-commit-date.outputs.value }}
  is-today:
    description: "A boolean indicating whether the current date and the latest commit date are the same (true) or different (false)."
    value: ${{ steps.is-today.outputs.value }}

runs:
  using: "composite"

  steps:
    - id: current-date
      shell: bash
      run: echo "value=$(date '+%Y-%m-%d')" >> "$GITHUB_OUTPUT"

    - id: latest-commit-date
      shell: bash
      run: echo "value=$(git log -1 --format="%cs" ${{ inputs.branch }})" >> "$GITHUB_OUTPUT"

    - id: is-today
      shell: bash
      run: |
        current_date=${{ steps.current-date.outputs.value }}
        latest_commit_date=${{ steps.latest-commit-date.outputs.value }}

        if [ "$current_date" == "$latest_commit_date" ]; then
          echo "value=true" >> "$GITHUB_OUTPUT"
        else
          echo "value=false" >> "$GITHUB_OUTPUT"
        fi
