name: latest-commit-date
description: "Get the date of the latest commit on a specific branch"

inputs:
  branch:
    description: "The branch to check history from"
    default: main

outputs:
  current-date:
    description: "Date at runtime"
    value: ${{ steps.current-date.outputs.value }}
  latest-commit-date:
    description: "Date of latest commit in Git history"
    value: ${{ steps.latest-commit-date.outputs.value }}
  is-today:
    description: "Defines is latest commit was pushed today"
    value: ${{ steps.is-today.outputs.value }}

runs:
  using: "composite"

  steps:
    - id: current-date
      shell: bash
      run: echo "value=$(date '+%Y-%m-%d')" >> "$GITHUB_OUTPUT"

    - id: latest-commit-date
      shell: bash
      run: echo "value=$(git log -1 --format="%cs" ${{ inputs.branch }})" >> "$GITHUB_OUTPUT"

    - id: is-today
      shell: bash
      run: |
        current_date=${{ steps.current-date.outputs.value }}
        latest_commit_date=${{ steps.latest-commit-date.outputs.value }}

        if [ "$current_date" == "$latest_commit_date" ]; then
          echo "value=true" >> "$GITHUB_OUTPUT"
        else
          echo "value=false" >> "$GITHUB_OUTPUT"
        fi
